const { SlashCommandBuilder } = require('@discordjs/builders');
const { Collection } = require('discord.js');

const atasozleri = [
        "Acele işe şeytan karışır.",
        "Ağaç yaş iken eğilir.",
        "Akıl akıldan üstündür.",
        "Ayağını yorganına göre uzat.",
        "Balık baştan kokar.",
        "Bugünün işini yarına bırakma.",
        "Cömert derler maldan ederler, yiğit derler candan ederler.",
        "Damlaya damlaya göl olur.",
        "Dil dile değmeden dil öğrenilmez.",
        "Dost kara günde belli olur.",
        "El el ile, değirmen yel ile.",
        "El elden üstündür.",
        "Gülü seven dikenine katlanır.",
        "İğneyi kendine, çuvaldızı başkasına batır.",
        "İşleyen demir ışıldar.",
        "Kendi düşen ağlamaz.",
        "Kendi yanan başkasını da yakar.",
        "Kervan yolda düzülür.",
        "Keskin sirke küpüne zarar verir.",
        "Komşu komşunun külüne muhtaçtır.",
        "Kurt kocayınca köpeğin maskarası olur.",
        "Kuzguna yavrusu şahin görünür.",
        "Mart kapıdan baktırır, kazma kürek yaktırır.",
        "Ne ekersen onu biçersin.",
        "Oğlan dayıya, kız halaya çeker.",
        "Sakla samanı gelir zamanı.",
        "Söz gümüşse sükût altındır.",
        "Su akar yolunu bulur.",
        "Tatlı dil yılanı deliğinden çıkarır.",
        "Taşıma su ile değirmen dönmez.",
        "Vakit nakittir.",
        "Yarım doktor candan eder, yarım hoca dinden eder.",
        "Yalancının mumu yatsıya kadar yanar.",
        "Yalnız taş duvar olmaz.",
        "Yanlış hesap Bağdat’tan döner.",
        "Yavuz hırsız ev sahibini bastırır.",
        "Zenginin malı züğürdün çenesini yorar.",
        "Bir elin nesi var, iki elin sesi var.",
        "Ayağını sürüyen yavaş, zamana uyan avşar.",
        "Başa gelen çekilir.",
        "Bıçak yarası geçer, dil yarası geçmez.",
        "Boş çuval ayakta durmaz.",
        "Dağ dağa kavuşmaz, insan insana kavuşur.",
        "Davulun sesi uzaktan hoş gelir.",
        "Deli deliden hoşlanır, imam ölüden.",
        "Dinsizin hakkından imansız gelir.",
        "Dikensiz gül olmaz.",
        "Görünen köy kılavuz istemez.",
        "Herkes gider Mersin’e, biz gideriz tersine.",
        "İki gönül bir olunca samanlık seyran olur.",
        "İşini bilmeyen muhtarı köy, köy gezer.",
        "Komşu kızı komşuya yakışır.",
        "Körle yatan şaşı kalkar.",
        "Köprüye gelince geçeriz.",
        "Minareyi çalan kılıfını hazırlar.",
        "Nerde hareket, orada bereket.",
        "Ok yaydan çıktı bir kere.",
        "Öfkeyle kalkan, zararla oturur.",
        "Para parayı çeker.",
        "Pire için yorgan yakılmaz.",
        "Sabreden derviş muradına ermiş.",
        "Sakınan göze çöp batar.",
        "Sana taş atana sen ekmek at.",
        "Tarlada izi olmayanın harmanda yüzü olmaz.",
        "Tilki tilkiliğini bildirinceye kadar post elden gider.",
        "Ucuzdur vardır illeti, pahalıdır vardır hikmeti.",
        "Üzüm üzüme baka baka kararır.",
        "Vakitsiz öten horozun başı kesilir.",
        "Yanında çocukla ekmek yeme.",
        "Yara bere olur, arkadaş ıra olur.",
        "Yazın başı pişenin, kışın aşı pişer.",
        "Yengeç yengece nasıl yürür diye sormuş.",
        "Yerinde söz söyleyen özür dilemek zorunda kalmaz.",
        "Yiğit namıyla anılır.",
        "Zararın neresinden dönersen kardır.",
        "Zemheride kar olur, ağustosun gözü yaşlı olur.",
        "Zincirleme kazalarla adam olacağımızı sanma.",
        "Zırhını giyenin kılıcı kesmez.",
        "Kervan yolda dizilir.",
        "Kuşlarla uçulur, köpeklerle havlanır.",
        "Kaz gelen yerden tavuk esirgenmez.",
        "Kör kuyulara düşen, eşeğine sarılır.",
        "Çok laf yalansız, çok para haramsız olmaz.",
        "Öküzün altında buzağı arama.",
        "Açma sırrını dostuna, o da söyler dostuna.",
        "Büyük lokma ye, büyük söz söyleme.",
        "Göz var izan var.",
        "Cennet anaların ayakları altındadır.",
        "Erken kalkan yol alır, erken evlenen döl alır.",
        "Zahmetsiz rahmet olmaz.",
        "Uzak durdun mu kurtarır seni sözü.",
        "Suyun üstünden akan balıkla yük taşıyamazsın.",
        "Gölgesiz ağaç bitmez, gölgesiz adam yetmez.",
        "Her yiğidin bir yoğurt yiyişi vardır.",
        "Hayırla gel, hayırla git.",
        "İnanma dostuna, saman doldurur postuna.",
        "Kızın var kaygı var, oğlun var dayı var.",
        "Akan su durulmaz.",
        "Mal mülk gözü karartır.",
        "Güzel gören, güzel düşünür.",
        "İyilik eden iyilik bulur.",
        "Körle yatan, şaşı kalkar.",
        "Yalnız taş duvar olmaz."
    ];


module.exports = {
    data: new SlashCommandBuilder()
        .setName('atasözü')
        .setDescription('Rastgele bir atasözü gönderir.'),

    cooldown: 5, // 5 saniye cooldown

    async execute(interaction) {
        const randomIndex = Math.floor(Math.random() * atasozleri.length);
        const randomAtasozu = atasozleri[randomIndex];

        await interaction.reply({ content: randomAtasozu, ephemeral: true });
    },
};
